# Generated by Django 2.1.5 on 2022-04-05 10:14

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('wilaya', models.CharField(choices=[('Wilaya', 'Adrar'), ('Wilaya', 'Chlef'), ('Wilaya', 'Laghouat'), ('Wilaya', 'Oum El Bouaghi'), ('Wilaya', 'Batna'), ('Wilaya', 'Béjaïa'), ('Wilaya', 'Biskra'), ('Wilaya', 'Bechar'), ('Wilaya', 'Blida'), ('Wilaya', 'Bouira'), ('Wilaya', 'Tamanrasset'), ('Wilaya', 'Tbessa'), ('Wilaya', 'Tlemcen'), ('Wilaya', 'Tiaret'), ('Wilaya', 'Tizi Ouzou'), ('Wilaya', 'Alger'), ('Wilaya', 'Djelfa'), ('Wilaya', 'Jijel'), ('Wilaya', 'Sétif'), ('Wilaya', 'Saefda'), ('Wilaya', 'Skikda'), ('Wilaya', 'Sidi Bel Abbes'), ('Wilaya', 'Annaba'), ('Wilaya', 'Guelma'), ('Wilaya', 'Constantine'), ('Wilaya', 'Medea'), ('Wilaya', 'Mostaganem'), ('Wilaya', "M'Sila"), ('Wilaya', 'Mascara'), ('Wilaya', 'Ouargla'), ('Wilaya', 'Oran'), ('Wilaya', 'El Bayadh'), ('Wilaya', 'Illizi'), ('Wilaya', 'Bordj Bou Arreridj'), ('Wilaya', 'Boumerdes'), ('Wilaya', 'El Tarf'), ('Wilaya', 'Tindouf'), ('Wilaya', 'Tissemsilt'), ('Wilaya', 'El Oued'), ('Wilaya', 'Khenchela'), ('Wilaya', 'Souk Ahras'), ('Wilaya', 'Tipaza'), ('Wilaya', 'Mila'), ('Wilaya', 'Ain Defla'), ('Wilaya', 'Naama'), ('Wilaya', 'Ain Temouchent'), ('Wilaya', 'Ghardaïa'), ('Wilaya', 'Relizane')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
