# Generated by Django 2.1.5 on 2022-04-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wilaya',
            field=models.CharField(choices=[('Wilaya', 'Adrar'), ('Wilaya', 'Chlef'), ('Wilaya', 'Laghouat'), ('Wilaya', 'Oum El Bouaghi'), ('Wilaya', 'Batna'), ('Wilaya', 'Béjaïa'), ('Wilaya', 'Biskra'), ('Wilaya', 'Bechar'), ('Wilaya', 'Blida'), ('Wilaya', 'Bouira'), ('Wilaya', 'Tamanrasset'), ('Wilaya', 'Tbessa'), ('Wilaya', 'Tlemcen'), ('Wilaya', 'Tiaret'), ('Wilaya', 'Tizi Ouzou'), ('Wilaya', 'Alger'), ('Wilaya', 'Djelfa'), ('Wilaya', 'Jijel'), ('Wilaya', 'Sétif'), ('Wilaya', 'Saefda'), ('Wilaya', 'Skikda'), ('Wilaya', 'Sidi Bel Abbes'), ('Wilaya', 'Annaba'), ('Wilaya', 'Guelma'), ('Wilaya', 'Constantine'), ('Wilaya', 'Medea'), ('Wilaya', 'Mostaganem'), ('Wilaya', "M'Sila"), ('Wilaya', 'Mascara'), ('Wilaya', 'Ouargla'), ('Wilaya', 'Oran'), ('Wilaya', 'El Bayadh'), ('Wilaya', 'Illizi'), ('Wilaya', 'Bordj Bou Arreridj'), ('Wilaya', 'Boumerdes'), ('Wilaya', 'El Tarf'), ('Wilaya', 'Tindouf'), ('Wilaya', 'Tissemsilt'), ('Wilaya', 'El Oued'), ('Wilaya', 'Khenchela'), ('Wilaya', 'Souk Ahras'), ('Wilaya', 'Tipaza'), ('Wilaya', 'Mila'), ('Wilaya', 'Ain Defla'), ('Wilaya', 'Naama'), ('Wilaya', 'Ain Temouchent'), ('Wilaya', 'Ghardaïa'), ('Wilaya', 'Relizane'), ('Livreur', '')], default='Livreur', max_length=10),
        ),
    ]
