# Generated by Django 4.0.4 on 2022-05-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='en_cours_livraison',
            field=models.CharField(default='', max_length=8000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='livres',
            field=models.CharField(default='', max_length=800000000),
        ),
    ]
