# Generated by Django 3.2.13 on 2022-05-15 23:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='num',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, validators=[accounts.models.clean_number]),
        ),
    ]
