# Generated by Django 3.2.13 on 2022-05-18 14:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='num',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[accounts.models.clean_number]),
        ),
    ]
