# Generated by Django 3.2.13 on 2022-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(default='0101-01-01 01:01', null=True),
        ),
    ]
