# Generated by Django 4.0.4 on 2022-05-11 19:59

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometpren', models.CharField(max_length=120, validators=[products.models.clean_nompren])),
                ('telephone', models.DecimalField(decimal_places=0, max_digits=10, validators=[products.models.clean_number])),
                ('telephone1', models.DecimalField(decimal_places=0, max_digits=10, validators=[products.models.clean_number])),
                ('wilaya', models.CharField(choices=[('Adrar', 'Adrar'), ('Chlef', 'Chlef'), ('Laghouat', 'Laghouat'), ('Oum El Bouaghi', 'Oum El Bouaghi'), ('Batna', 'Batna'), ('Béjaïa', 'Béjaïa'), ('Biskra', 'Biskra'), ('Bechar', 'Bechar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tbessa', 'Tbessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Sétif'), ('Saefda', 'Saefda'), ('Skikda', 'Skikda'), ('Sidi Bel Abbes', 'Sidi Bel Abbes'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Medea', 'Medea'), ('Mostaganem', 'Mostaganem'), ("M'Sila", "M'Sila"), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'El Bayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Boumerdes', 'Boumerdes'), ('El Tarf', 'El Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'El Oued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Souk Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Ain Defla', 'Ain Defla'), ('Naama', 'Naama'), ('Ain Temouchent', 'Ain Temouchent'), ('Ghardaïa', 'Ghardaïa'), ('Relizane', 'Relizane')], max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('numerocommande', models.DecimalField(decimal_places=0, max_digits=10)),
                ('poids', models.DecimalField(decimal_places=0, max_digits=4)),
                ('remarque', models.TextField(max_length=100)),
                ('produit', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('typeenvoi', models.CharField(choices=[('V', '---------'), ('livraison', 'livraison'), ('échange', 'échange'), ('Pick up', 'Pick up'), ('recouvrement', 'recouvrement')], default='V', max_length=100)),
                ('typeprestation', models.CharField(choices=[('V', '---------'), ('à domicile', 'à domicile'), ('Stop desk', 'Stop desk')], default='V', max_length=100)),
                ('pretaexpedier', models.BooleanField(default=True)),
                ('enramassage', models.BooleanField(default=False)),
                ('entransit', models.BooleanField(default=False)),
                ('enhub', models.BooleanField(default=False)),
                ('enlivraison', models.BooleanField(default=False)),
                ('suspendus', models.BooleanField(default=False)),
                ('nonencaissés', models.BooleanField(default=False)),
                ('encaissésnonpayes', models.BooleanField(default=False)),
                ('paiementsprets', models.BooleanField(default=False)),
                ('chezclient', models.BooleanField(default=False)),
                ('retoursentraitement', models.BooleanField(default=False)),
                ('retoursprets', models.BooleanField(default=False)),
                ('email', models.EmailField(default='soraya@gmail.com', max_length=100)),
            ],
        ),
    ]
