# Generated by Django 2.1.5 on 2022-04-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chezclient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='encaissésnonpayes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enhub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enlivraison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enramassage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='entransit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='nonencaissés',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='paiementsprets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pretaexpedier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='retoursentraitement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='retoursprets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='suspendus',
            field=models.BooleanField(default=False),
        ),
    ]
