# Generated by Django 3.2.13 on 2022-05-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commune',
            field=models.CharField(max_length=200),
        ),
    ]
