# Generated by Django 4.0.4 on 2022-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='livreur',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
