# Generated by Django 3.2.13 on 2022-05-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remarque',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
