# Generated by Django 2.1.5 on 2022-04-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220414_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.CharField(default='this is an email', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='typeenvoi',
            field=models.CharField(choices=[('V', '---------'), ('LI', 'livraison'), ('EC', 'échange'), ('PU', 'Pick up'), ('RE', 'recouvrement')], default='V', max_length=100),
        ),
    ]
