# Generated by Django 4.0.4 on 2022-05-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='livreur',
        ),
        migrations.AddField(
            model_name='product',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
