# Generated by Django 3.2.13 on 2022-05-15 10:30

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_remarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payés',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='telephone1',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, validators=[products.models.clean_number]),
        ),
    ]
