# Generated by Django 2.1.5 on 2022-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220415_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.EmailField(default='soraya@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, primary_key=True, serialize=False),
        ),
    ]
