# Generated by Django 4.0.4 on 2022-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_commune_alter_product_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
