# Generated by Django 3.2.13 on 2022-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220515_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='produit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='remarque',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
