# Generated by Django 4.0.4 on 2022-05-09 15:11

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='telephone',
            field=models.DecimalField(decimal_places=0, max_digits=10, unique=True, validators=[products.models.clean_number]),
        ),
    ]
