# Generated by Django 3.2.13 on 2022-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220518_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.DecimalField(decimal_places=0, max_digits=10000)),
                ('comment', models.TextField()),
            ],
        ),
    ]
