# Generated by Django 4.0.4 on 2022-05-09 15:49

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nometpren',
            field=models.CharField(max_length=120, validators=[products.models.clean_nompren]),
        ),
        migrations.AlterField(
            model_name='product',
            name='telephone',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[products.models.clean_number]),
        ),
        migrations.AlterField(
            model_name='product',
            name='telephone1',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[products.models.clean_number]),
        ),
    ]
