# Generated by Django 3.2.13 on 2022-05-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id_user',
            field=models.DecimalField(decimal_places=0, max_digits=10000, null=True),
        ),
    ]
