# Generated by Django 4.0.4 on 2022-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_nometpren_alter_product_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='typeenvoi',
            field=models.CharField(choices=[('V', '---------'), ('livraison', 'livraison'), ('échange', 'échange'), ('Pick up', 'Pick up'), ('recouvrement', 'recouvrement')], default='V', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='typeprestation',
            field=models.CharField(choices=[('V', '---------'), ('à domicile', 'à domicile'), ('Stop desk', 'Stop desk')], default='V', max_length=100),
        ),
    ]
